{{/*
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if empty .Values.conf.dcagent.keystone_authtoken.auth_uri -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.dcagent.keystone_authtoken "auth_uri" -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.keystone_authtoken.auth_url -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.dcagent.keystone_authtoken "auth_url" -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.keystone_authtoken.region_name -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "region_name" .Values.endpoints.identity.auth.dcagent.region_name -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.keystone_authtoken.project_name -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "project_name" .Values.endpoints.identity.auth.dcagent.project_name -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.keystone_authtoken.project_domain_name -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "project_domain_name" .Values.endpoints.identity.auth.dcagent.project_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.keystone_authtoken.user_domain_name -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "user_domain_name" .Values.endpoints.identity.auth.dcagent.user_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.keystone_authtoken.username -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "username" .Values.endpoints.identity.auth.dcagent.username -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.keystone_authtoken.password -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "password" .Values.endpoints.identity.auth.dcagent.password -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.keystone_authtoken.interface -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "interface" (default "internal" .Values.endpoints.identity.auth.dcagent.interface) -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.endpoint_cache.auth_uri -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.dcagent.keystone_authtoken "auth_uri" -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.endpoint_cache.region_name -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "region_name" .Values.endpoints.identity.auth.dcagent.region_name -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.endpoint_cache.project_name -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "project_name" .Values.endpoints.identity.auth.dcagent.project_name -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.endpoint_cache.project_domain_name -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "project_domain_name" .Values.endpoints.identity.auth.dcagent.project_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.endpoint_cache.user_domain_name -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "user_domain_name" .Values.endpoints.identity.auth.dcagent.user_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.endpoint_cache.username -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "username" .Values.endpoints.identity.auth.dcagent.username -}}
{{- end -}}
{{- if empty .Values.conf.dcagent.endpoint_cache.password -}}
{{- $_ := set .Values.conf.dcagent.keystone_authtoken "password" .Values.endpoints.identity.auth.dcagent.password -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: dcagent-etc
type: Opaque
data:
  dcagent.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.dcagent | b64enc }}
  logging.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.logging | b64enc }}
