#
# Copyright (c) 2025 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: dcagent
  labels:
    chart_group: dcagent
spec:
  releaseName: dcagent
  chart:
    spec:
      chart: dcagent
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: dcagent-static-overrides
      valuesKey: dcagent-static-overrides.yaml
    - kind: Secret
      name: dcagent-system-overrides
      valuesKey: dcagent-system-overrides.yaml
