{{/*
#
# SPDX-License-Identifier: Apache-2.0
#
*/}}

{{- if empty .Values.conf.dcmanager.database.connection -}}
{{- $connection := tuple "oslo_db" "internal" "dcmanager" "postgresql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup" -}}
{{- $_ := set .Values.conf.dcmanager.database "connection" $connection -}}
{{- end -}}
{{- if empty .Values.conf.dcmanager.DEFAULT.sql_connection -}}
{{- $_ := tuple "oslo_db" "internal" "dcmanager" "postgresql" . | include "helm-toolkit.endpoints.authenticated_endpoint_uri_lookup"| set .Values.conf.dcmanager.DEFAULT "sql_connection" -}}
{{- end -}}
{{- if empty .Values.conf.dcmanager.keystone_authtoken.auth_uri -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.dcmanager.keystone_authtoken "auth_uri" -}}
{{- end -}}
{{- if empty .Values.conf.dcmanager.keystone_authtoken.auth_url -}}
{{- $_ := tuple "identity" "internal" "api" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup"| set .Values.conf.dcmanager.keystone_authtoken "auth_url" -}}
{{- end -}}
{{- if empty .Values.conf.dcmanager.keystone_authtoken.region_name -}}
{{- $_ := set .Values.conf.dcmanager.keystone_authtoken "region_name" .Values.endpoints.identity.auth.dcmanager.region_name -}}
{{- end -}}
{{- if empty .Values.conf.dcmanager.keystone_authtoken.project_name -}}
{{- $_ := set .Values.conf.dcmanager.keystone_authtoken "project_name" .Values.endpoints.identity.auth.dcmanager.project_name -}}
{{- end -}}
{{- if empty .Values.conf.dcmanager.keystone_authtoken.project_domain_name -}}
{{- $_ := set .Values.conf.dcmanager.keystone_authtoken "project_domain_name" .Values.endpoints.identity.auth.dcmanager.project_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcmanager.keystone_authtoken.user_domain_name -}}
{{- $_ := set .Values.conf.dcmanager.keystone_authtoken "user_domain_name" .Values.endpoints.identity.auth.dcmanager.user_domain_name -}}
{{- end -}}
{{- if empty .Values.conf.dcmanager.keystone_authtoken.username -}}
{{- $_ := set .Values.conf.dcmanager.keystone_authtoken "username" .Values.endpoints.identity.auth.dcmanager.username -}}
{{- end -}}
{{- if empty .Values.conf.dcmanager.keystone_authtoken.password -}}
{{- $_ := set .Values.conf.dcmanager.keystone_authtoken "password" .Values.endpoints.identity.auth.dcmanager.password -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: dcmanager-etc
type: Opaque
data:
  dcmanager.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.dcmanager | b64enc }}
  logging.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.logging | b64enc }}
