#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

namespace: distributed-cloud
resources:
  - helmrelease.yaml
secretGenerator:
  - name: dcorch-static-overrides
    files:
      - dcorch-static-overrides.yaml
  - name: dcorch-system-overrides
    files:
      - dcorch-system-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
