#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: dcmanager
  labels:
    chart_group: dcmanager
spec:
  releaseName: dcmanager
  chart:
    spec:
      chart: dcmanager
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: dcmanager-static-overrides
      valuesKey: dcmanager-static-overrides.yaml
    - kind: Secret
      name: dcmanager-system-overrides
      valuesKey: dcmanager-system-overrides.yaml
